"""Mako template for Alembic migration scripts."""

"""initial schema

Revision ID: 2169eca98cdc
Revises: 
Create Date: 2026-08-24 11:42:52.173702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2169eca98cdc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('deviation_pct', sa.Float(), nullable=False),
    sa.Column('expected_bbl_d', sa.Float(), nullable=False),
    sa.Column('actual_bbl_d', sa.Float(), nullable=False),
    sa.Column('contributing_features', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_events_asset_id'), 'anomaly_events', ['asset_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('field', sa.String(length=120), nullable=False),
    sa.Column('basin', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('onstream_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('baseline_qi', sa.Float(), nullable=False),
    sa.Column('baseline_di', sa.Float(), nullable=False),
    sa.Column('baseline_b', sa.Float(), nullable=False),
    sa.Column('operating_cost_usd_m', sa.Float(), nullable=False),
    sa.Column('intervention_cost_usd_m', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('series', sa.JSON(), nullable=False),
    sa.Column('feature_importance', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_runs_asset_id'), 'forecast_runs', ['asset_id'], unique=False)
    op.create_table('model_registry',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('task', sa.String(length=80), nullable=False),
    sa.Column('algorithm', sa.String(length=120), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provenance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_name', sa.String(length=160), nullable=False),
    sa.Column('publisher', sa.String(length=80), nullable=False),
    sa.Column('data_class', sa.String(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('integrity_score', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aips_score', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_runs_asset_id'), 'score_runs', ['asset_id'], unique=False)
    op.create_table('simulation_sessions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('scenario', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticks_sent', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_sessions_asset_id'), 'simulation_sessions', ['asset_id'], unique=False)
    op.create_table('monthly_production',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('oil_bbl_d', sa.Float(), nullable=False),
    sa.Column('expected_bbl_d', sa.Float(), nullable=False),
    sa.Column('gas_mmcf_d', sa.Float(), nullable=False),
    sa.Column('water_cut_pct', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('provenance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_production_asset_id'), 'monthly_production', ['asset_id'], unique=False)
    op.create_index(op.f('ix_monthly_production_period'), 'monthly_production', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_production_period'), table_name='monthly_production')
    op.drop_index(op.f('ix_monthly_production_asset_id'), table_name='monthly_production')
    op.drop_table('monthly_production')
    op.drop_index(op.f('ix_simulation_sessions_asset_id'), table_name='simulation_sessions')
    op.drop_table('simulation_sessions')
    op.drop_index(op.f('ix_score_runs_asset_id'), table_name='score_runs')
    op.drop_table('score_runs')
    op.drop_table('provenance_records')
    op.drop_table('model_registry')
    op.drop_index(op.f('ix_forecast_runs_asset_id'), table_name='forecast_runs')
    op.drop_table('forecast_runs')
    op.drop_table('assets')
    op.drop_index(op.f('ix_anomaly_events_asset_id'), table_name='anomaly_events')
    op.drop_table('anomaly_events')
    # ### end Alembic commands ###
